#!/usr/bin/env bash
#
# Registers a JFrog Platform server with the jf CLI from credentials sops-nix
# has decrypted, so ~/.jfrog is written by jf itself rather than generated by
# Nix. Called from home/profiles/lely/artifactory.nix on every activation, and
# runnable by hand after rotating the credential.
#
# Usage:
#   jfrog-config.sh <server-id> <machine-file> <username-file> <password-file>
#
# Arguments:
#   server-id     - label jf stores the deployment under, referenced later
#                   as --server-id
#   machine-file  - file holding the bare hostname; the URL is https://<host>
#   username-file - file holding the login
#   password-file - file holding the password or identity token
#
# Outputs:
#   Writes progress to stdout and diagnostics to stderr.
#   Rewrites this server's entry in ~/.jfrog.
#
# Returns:
#   0 on success, including when the secrets are absent; non-zero from jf.

set -o errexit -o nounset -o pipefail

#shellcheck source=./../../../lib/common.sh
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/../../../lib/common.sh"

[[ $# -eq 4 ]] || die "usage: jfrog-config.sh <server-id> <machine-file> <username-file> <password-file>"

SERVER_ID="${1}"
MACHINE_FILE="${2}"
USERNAME_FILE="${3}"
PASSWORD_FILE="${4}"

command -v jf >/dev/null || die "jf is not on PATH; is jfrog-cli in home.packages?"

# Not an error. A machine without the work age identity activates fine, it
# just ends up without Artifactory credentials; preflight.sh is what insists
# on the secrets checkout for this profile.
for secret_file in "${MACHINE_FILE}" "${USERNAME_FILE}" "${PASSWORD_FILE}"; do
	if [[ ! -r ${secret_file} ]]; then
		warn "no decrypted secret at ${secret_file}, leaving ~/.jfrog alone"
		exit 0
	fi
done

# --password-stdin keeps the credential out of the process table.
# --overwrite makes repeated activations idempotent rather than a hard error
# on the second run.
# --basic-auth-only and --enc-password=false keep this offline: without them
# jf calls the platform to encrypt the password and to mint an hourly
# refreshing access token, which fails whenever activation happens off VPN.
log "Configuring jf server '${SERVER_ID}'"
jf config add "${SERVER_ID}" \
	--url="https://$(cat "${MACHINE_FILE}")" \
	--user="$(cat "${USERNAME_FILE}")" \
	--password-stdin \
	--basic-auth-only \
	--enc-password=false \
	--interactive=false \
	--overwrite \
	<"${PASSWORD_FILE}"

jf config use "${SERVER_ID}"
