{
    config,
    lib,
    pkgs,
    link,
    ...
}:
let
    inherit (lib) attrValues concatMap filterAttrs;
    inherit (pkgs.vimPlugins.nvim-treesitter) grammarPlugins;

    codelldb = pkgs.writeShellScriptBin "codelldb" ''
        exec ${pkgs.vscode-extensions.vadimcn.vscode-lldb}/share/vscode/extensions/vadimcn.vscode-lldb/adapter/codelldb "$@"
    '';

    enabled = filterAttrs (_: language: language.enable) config.languages;
    collect = attribute: lib.unique (concatMap (language: language.${attribute}) (attrValues enabled));

    grammars = collect "grammars";

    # Neovim ships these in $out/lib/nvim/parser, already on the runtimepath.
    # Packaging them again would put two copies of one grammar on the path, and
    # which loads would depend on its order.
    bundledGrammars = [
        "c"
        "lua"
        "markdown"
        "markdown_inline"
        "query"
        "vim"
        "vimdoc"
    ];

    wanted = lib.subtractLists bundledGrammars grammars;
    unpackaged = lib.filter (grammar: !(builtins.hasAttr grammar grammarPlugins)) wanted;

    luaList = items: "{ " + lib.concatMapStringsSep ", " (item: ''"${item}"'') items + " }";

    manifest = pkgs.writeTextFile {
        name = "nvim-nix-languages";
        destination = "/lua/nix_languages.lua";
        text = ''
            -- Generated by home/modules/nvim.nix from `languages`. Do not edit.
            return {
            filetypes = ${luaList (collect "filetypes")},
            grammars = ${luaList grammars},
            servers = ${luaList (collect "servers")},
            }
        '';
    };

    # Only blink.cmp's build uses this, through $NVIM_NIX_RUNTIME/bin. It stays off
    # PATH so it doesn't shadow a project's rustup toolchain, such as the one in
    # the dev container image.
    # TODO: Once nix manages nvim plugins, take blink.cmp from nixpkgs (or its own
    # flake). That builds the fuzzy matcher in the derivation, so this can go.
    rustToolchain = pkgs.buildEnv {
        name = "nvim-nix-rust";
        paths = [
            pkgs.cargo
            pkgs.rustc
        ];
        pathsToLink = [ "/bin" ];
    };

    nvimRuntime = pkgs.symlinkJoin {
        name = "nvim-nix-runtime";
        paths = [
            manifest
            rustToolchain
        ]
        ++ map (grammar: grammarPlugins.${grammar}) wanted;
    };
in
{
    imports = [
        ./fzf.nix
        ./ripgrep.nix
    ];

    assertions = [
        {
            assertion = unpackaged == [ ];
            message = "No nvim-treesitter grammar in nixpkgs for: ${lib.concatStringsSep ", " unpackaged}";
        }
    ];

    home.packages = with pkgs; [
        neovim
        codelldb

        fd # fzf-lua file provider
    ];

    home.sessionVariables.NVIM_NIX_RUNTIME = "${nvimRuntime}";

    xdg.configFile."nvim".source = link "config/nvim";
}
