#!/bin/bash

# Allow dynamic sourcing in known locations
# shellcheck disable=SC1090,SC1091

# Nix
for _nix_profile in \
	/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh \
	/nix/var/nix/profiles/default/etc/profile.d/nix.sh \
	"$HOME/.nix-profile/etc/profile.d/nix.sh"; do
	[ -f "$_nix_profile" ] && . "$_nix_profile" && break
done
unset _nix_profile

[ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ] &&
	. "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"

# INFO If not running interactively, then only source and skip the rest
[[ $- != *i* ]] && return

# Completions
source /etc/profile.d/bash_completion.sh

source "${XDG_CONFIG_HOME:-$HOME/.config}/bash/eza.sh"
source "${XDG_CONFIG_HOME:-$HOME/.config}/bash/history_config.sh"
source "${XDG_CONFIG_HOME:-$HOME/.config}/fzf/fzf.sh"

# Aliases
alias ld='lazydocker'
alias lg='lazygit'
alias top='btop'
alias vi='nvim'

# Exports
export EDITOR="nvim"
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"
export NAVI_PATH="$HOME/.config/navi/cheats"

# Start up executions
oh-my-posh disable notice

# Shell integrations
eval "$(navi widget bash)"
eval "$(zoxide init --cmd cd bash)"
eval "$(oh-my-posh init bash --config ~/.config/oh-my-posh/theme.toml)"
